version: "3.2"
services:
  api:
    image: fastapi_api
    container_name: ml_api
    build:
      context: ./api
      target: build
    ports:
      - "80:5000"
#    environment:

    depends_on:
      - redis
      - model
    volumes:
      - ./api/app.db:/src/app.db

  redis:
    image: redis:6.2.6
#    ports:
#      - "6379:6379"

  model:
    image: ml_service
    build:
      context: ./model
      target: build
    depends_on:
      - redis
